name: mi_app_ingles
description: Una app para aprender inglés con lecciones y zona VIP.
publish_to: 'none' # Esto evita que se publique en pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  flutter_tts: ^3.5.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    # Aquí puedes añadir imágenes u otros recursos si los agregas

